version: "3.7"

services:
  django_app:
    build: ./django_project
    container_name: django_app
    restart: always
    expose:
      - 8080

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
