name: Zwitter

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r django_project/requirements.txt
        pip install flake8
        pip install pytest
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest django_project -v
    - name: Set up Containers
      run: |
        docker-compose build
        docker-compose up -d
        python webhook.py
    - name: Run Connection Test
      run: |
        curl -f -I http://127.0.0.1:80
    - name: Kill Containers
      run: |
        docker down
    - name: deploy
      env: |
        KEY: ${{ secrets.KEY }}
      run: |
        curl http://ec2-18-217-114-209.us-east-2.compute.amazonaws.com/webhook -X POST -H "Content-Type: application/json" -d '{"key": "${KEY}"}'
